"""
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# first two terms
n1 = 0
n2 = 1
#count = 0
values = []
total = 0


while n1 < 4000000:
      values.append(n1)
      nth = n1 + n2
      n1 = n2
      n2 = nth

for value in values:
    if value % 2 == 0:
       total += value

print(total)